"use client";
import { useState } from "react";
import { Button, Badge, PageTitle, Stat, Search, Table, Modal, RecordForm, Person } from "@/components/ui";
import { money, dateLabel, statusOf } from "@/lib/erp-utils";
import { Users, Package, ShoppingCart, DollarSign, Building2, Clock3, AlertTriangle, BarChart3, FileText, UserRound, Boxes, TrendingUp, Wallet, CircleDollarSign, ClipboardList, ContactRound, PackageSearch, ArrowDownToLine, Printer, Plus, ArrowUpRight } from "lucide-react";

export default function Settings({ darkMode, setDarkMode }) {
  const [company,setCompany]=useState("BizManager Inc.");const [email,setEmail]=useState("admin@bizmanager.example");const [currency,setCurrency]=useState("USD ($)");const [saved,setSaved]=useState(false);
  return <><PageTitle title="Settings" description="Configure workspace preferences."/><div className="settings-layout"><nav className="panel settings-nav"><button className="selected">General</button><button>Appearance</button><button>Notifications</button><button>Account</button></nav><section className="panel settings-panel"><div className="panel-heading"><div><h2>General settings</h2><p>Workspace details and regional preferences.</p></div></div><form className="settings-form" onSubmit={e=>{e.preventDefault();setSaved(true)}}><label className="field"><span>Company name</span><input required value={company} onChange={e=>setCompany(e.target.value)}/></label><label className="field"><span>Administrator email</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Display currency</span><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD ($)</option><option>ETB (Br)</option><option>EUR (€)</option><option>GBP (£)</option></select></label><div className="setting-toggle"><div><strong>Dark mode</strong><p>Use a darker appearance for this browser session.</p></div><button type="button" className={`switch ${darkMode?"on":""}`} aria-pressed={darkMode} onClick={()=>setDarkMode(!darkMode)}><span/></button></div><div className="modal-actions"><Button type="submit">Save preferences</Button></div>{saved&&<p className="success">Preferences saved for this page session only.</p>}</form></section></div></>;
}
